#!/usr/bin/env ruby

require 'slim'
require 'sinatra'

Slim::Engine.set_options pretty: true

set :bind, '0.0.0.0'
set :port, 3000
set :root, File.expand_path('..', __dir__)
set :views, Dir.pwd
set :public_folder, Dir.pwd

get '/' do
  files = Dir["*.slim"]
  result = ["<style>* { font-family: arial; text-align: center; font-size: 20px; line-height: 1.5; }</style>"]
  files.each do |file|
    basename = File.basename file, ".slim"
    result << %Q[<a href="#{basename}">#{basename}</a><br>]
  end
  result.join "\n"
end

get '/*' do
  page = params[:splat].first
  halt 404 unless File.exist? "#{page}.slim"
  slim page.to_sym
end

